name = "pika"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "pika-db"
database_id = "55bfb2fc-4085-4670-9611-da2f1eee4888"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "pika"
